spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: recipe
  datasource:
    url: jdbc:postgresql://localhost:5432/recipe
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    operations-sorter: alpha
    path: /documentation.html
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:recipe_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  sql:
    init:
      platform: h2
